spring.application.name=vsCatalog
server.port=8080

spring.datasource.url=jdbc:mysql://mysql-db:3306/catalog_db
spring.datasource.username=catalog_user
spring.datasource.password=catalog_password
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true