spring.application.name=vsBFF
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/<TENANT_ID>/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://<API_CLIENT_ID>